# Force OS X.
language: objective-c
os: osx
env: OSX=10.11
osx_image: xcode7.3
rvm: 2.3.1

before_script:
  - sudo rm -rf /usr/local/bin/brew /usr/local/.??* /Applications/Xcode.app /Library/Developer/CommandLineTools /opt/homebrew-cask/Caskroom
  - sudo pkgutil --forget com.apple.pkg.CLTools_Executables

script:
  - ./bin/setup
